export const commodityInitialState = {
    company: '',
    entity_code: '',
    partner_code: '',
    commodity: '',
}

export const warehouseInitialState = {
    company: '',
    entity_code: '',
    warehouse_order: "",
    warehouse_code: '',
    warehouse_name: '',
    warehouse_address: '',
    warehouse_country: '',
    warehouse_postcode: '',
    warehouse_telephone: '',
    warehouse_contact: '',
    warehouse_email: '',
    warehouse_active: '',
}

export const customerIntialState={
    partner_code: "",
    partner_active: "",
    partner_ref: "",
    partner_name: "",
    partner_address1: "",
    partner_address2: "",
    partner_address3: "",
    partner_city: "",
    partner_state: "",
    partner_country: "",
    partner_country_iso: "",
    partner_postcode: "",
    partner_tel_1: "",
    partner_tel_2: "",
    partner_tel_3: "",
    partner_fax_1: "",
    partner_telex: "",
    partner_contact_1: "",
    partner_contact_2: "",
    partner_sales_person: "",
    partner_cs_person: "",
    partner_email_1: "",
    partner_website: "",
    partner_gst_reg: "",
    partner_group: "",
    partner_terms: "",
    partner_currency: "",
    sales_type: "",
    partner_name_zh: "",
    partner_address_zh: "",
    khmer_name: "",
    khmer_address: "",
    partner_crno: "",
    partner_name_khmer: "",
    partner_address_khmer: "",
    partner_name_vn: "",
    partner_address_vn: "",
    partner_name_th: "",
    partner_address_th: "",
    partner_name_mm: "",
    partner_address_mm: "",
    partner_name_tw: "",
    partner_address_tw: "",
    partner_iso_code: "",
    partner_iata_code: "",
    partner_iata_account: "",
    partner_scac_code: "",
    partner_whatsapp: "",
    partner_wechat: "",
    partner_facebook: "",
    partner_line_id: "",
    partner_instagram: "",
    partner_class: "",
    wca_no: "",
    lognet_no: "",
    gaa_no: "",
    egln_no: "",
    partner_uen: "",
    partner_iec_code: "",
    partner_usci_code: "",
    partner_raca_code: "",
    iec_code: "",
    usci_code: "",
    raca_code: "",
    partner_status: 'N',
    partner_network: "",
    partner_category: "",
    partner_logo: "",
    partner_type: "",
    partner_roles: "",
    partner_term: 0,
    choose_sel: "N",
    partner_source: "",
    peppol_id: "",
    api_user: "",
    api_password: "",
    api_key: "",
    partner_label_file: "",
    role_wms: "N",
    role_lastmile: "N",
    role_contractor: "N",
    company: "",
    entity_code: ""
};
// both have time
export const inventoryDetailIntialState={
    company: "",
    entity_code: "",
    warehouse_code: "",
    order_ref: "",
    row_ref: "",
    choose_sel: "",
    sku_category: "",
    location_code: "",
    sku_code: "",
    sku_desc: "",
    sku_uom: "",
    sku_qty: 0,
    sku_weight: 0,
    sku_cbm: 0,
    container_no: "",
    pallet_no: "",
    carton_no: "",
    mfg_date: "",
    expiry_date: "",
    reference1: "",
    reference2: "",
    reference3: "",
    reference4: "",
    damage_status: "",
    damage_code: "",
    item_comments: "",
    post_status: "",
    post_date: "",
    post_time: "",
    post_user: "",
    post_ref: "",
    batch_no: "",
    actual_date: new Date().toISOString().split('T')[0], // Default to today's date
    put_ref: "",
    put_done: "",
    pick_ref: "",
    pick_done: "",
    block_status: "",
    block_date: "",
    block_user: "",
    used_in_release: "",
    itemsign: 0
};

export const inventoryHeaderIntialState={
  company: "",
  entity_code: "",
  partner_code: "",
  commodity: "",
  order_ref: "",
  order_date: '',
  order_desc: "",
  order_type: "",
  order_mode: "",
  goods_type: "",
  order_status: "",
  status_date: '',
  po_number: "",
  invoice_no: "",
  master_ref: "",
  booking_ref: "",
  partner_name: "",
  tracking_ref: ""
};
// don't have update date and user 

export const wmsSortingIntialState={
  company: "",
  entity_code: "",
//   sort_id: 0,
  warehouse_code: "",
  commodity: "",
  order_ref: "",
  sort_type: "",
  sku_code: "",
  sku_qty: 0,
  reference1: "",
  image_link1: "",
  image_link2: "",
  image_link3: "",
  choose_sel: "",
  post_status: ""
};
export const receivingIntialState={
  company: "",
  entity_code: "",
//   rec_id: 0,
  warehouse_code: "",
  commodity: "",
  order_ref: "",
  container_no: "",
  pallet_no: "",
  carton_no: "",
  sku_code: "",
  sku_qty: 0,
  sku_uom: "",
  reference1: "",
  image_link1: "",
  image_link2: "",
  image_link3: "",
  choose_sel: "",
  post_status: "",
  sku_desc:""
};
export const wmsTransferIntialState={
  company: "",
  entity_code: "",
//   transfer_id: 0,
  from_warehouse: "",
  to_warehouse: "",
  from_location: "",
  source_type: "",
  source_value: "",
  to_location: "",
  target_type: "",
  target_value: "",
  sku_code: "",
  sku_qty: 0,
  reference1: "",
  image_link1: "",
  image_link2: "",
  image_link3: "",
  choose_sel: "",
  post_status: ""
};
export const wmsPickIntialState={
  company: "",
  entity_code: "",
//   pick_id: 0,
  warehouse_code: "",
  order_ref: "",
  pick_ref: "",
  pick_location: "",
  sku_code: "",
  sku_qty: 0,
  reference1: "",
  image_link1: "",
  image_link2: "",
  image_link3: "",
  choose_sel: "",
  post_status: ""
};
export const wmsPackIntialState={
  company: "",
  entity_code: "",
//   pack_id: 0,
  warehouse_code: "",
  order_ref: "",
  pack_location: "",
  source_type: "",
  source_value: "",
  target_type: "",
  target_value: "",
  sku_code: "",
  sku_desc: "",
  sku_qty: 0,
  reference1: "",
  image_link1: "",
  image_link2: "",
  image_link3: "",
  choose_sel: "",
  post_status: ""
};
export const wmsStockTakeIntialState={
  company: "",
  entity_code: "",
//   stock_take_id: 0,
  warehouse_code: "",
  location_code: "",
  sku_code: "",
  sku_desc: "",
  sku_qty:"",
  data_origin: "",
  choose_sel: "",
  post_status: "",
  image_link1: "",
  image_link2: "",
  image_link3: "",
  commodity: ""
};
export const wmsPutAwayIntialState={
    company: "",
    entity_code: "",
  //   put_id: 0,
    warehouse_code: "",
    order_ref: "",
    from_location: "",
    source_type: "",
    source_value: "",
    to_location: "",
    target_type: "",
    target_value: "",
    sku_code: "",
    sku_qty: 0,
    reference1: "",
    choose_sel: "",
    post_status: "",
    image_link1: "",
    image_link2: "",
    image_link3: ""
  };
  
  
export const xwmsFeedbackIntialState={
  company: "",
  entity_code: "",
//   feedback_id: 0,
  user_id: "",
  user_email: "",
  feedback_date: "",
  feedback_subject: "",
  feedback_description: "",
  create_date: ""
};

