export const commodityInitialState = {
    company: '',
    entity_code: '',
    partner_code: '',
    commodity: '',
}
// Table: wms_commodity
// Columns:
//   - company (character varying, max length: 20) NOT NULL      
//   - entity_code (character varying, max length: 20) NOT NULL  
//   - partner_code (character varying, max length: 20) NOT NULL 
//   - commodity (character varying, max length: 30) NOT NULL    
//   - create_user (character varying, max length: 10) NOT NULL  
//   - create_date (date) NOT NULL
//   - create_time (time without time zone) NOT NULL
//   - update_user (character varying, max length: 10) NOT NULL  
//   - update_date (date) NOT NULL
//   - update_time (time without time zone) NOT NULL

export const warehouseInitialState = {
    company: '',
    entity_code: '',
    warehouse_order: null,
    warehouse_code: '',
    warehouse_name: '',
    warehouse_address: '',
    warehouse_country: '',
    warehouse_postcode: '',
    warehouse_telephone: '',
    warehouse_contact: '',
    warehouse_email: '',
    warehouse_active: '',
}
export const customerIntialState={
    partner_code: "",
    partner_active: "",
    partner_ref: "",
    partner_name: "",
    partner_address1: "",
    partner_address2: "",
    partner_address3: "",
    partner_city: "",
    partner_state: "",
    partner_country: "",
    partner_country_iso: "",
    partner_postcode: "",
    partner_tel_1: "",
    partner_tel_2: "",
    partner_tel_3: "",
    partner_fax_1: "",
    partner_telex: "",
    partner_contact_1: "",
    partner_contact_2: "",
    partner_sales_person: "",
    partner_cs_person: "",
    partner_email_1: "",
    partner_website: "",
    partner_gst_reg: "",
    partner_group: "",
    partner_terms: "",
    partner_currency: "",
    sales_type: "",
    partner_name_zh: "",
    partner_address_zh: "",
    khmer_name: "",
    khmer_address: "",
    partner_crno: "",
    partner_name_khmer: "",
    partner_address_khmer: "",
    partner_name_vn: "",
    partner_address_vn: "",
    partner_name_th: "",
    partner_address_th: "",
    partner_name_mm: "",
    partner_address_mm: "",
    partner_name_tw: "",
    partner_address_tw: "",
    partner_iso_code: "",
    partner_iata_code: "",
    partner_iata_account: "",
    partner_scac_code: "",
    partner_whatsapp: "",
    partner_wechat: "",
    partner_facebook: "",
    partner_line_id: "",
    partner_instagram: "",
    partner_class: "",
    wca_no: "",
    lognet_no: "",
    gaa_no: "",
    egln_no: "",
    partner_uen: "",
    partner_iec_code: "",
    partner_usci_code: "",
    partner_raca_code: "",
    iec_code: "",
    usci_code: "",
    raca_code: "",
    partner_status: 'N',
    partner_network: "",
    partner_category: "",
    partner_logo: "",
    partner_type: "",
    partner_roles: "",
    partner_term: 0,
    choose_sel: "N",
    partner_source: "",
    peppol_id: "",
    api_user: "",
    api_password: "",
    api_key: "",
    partner_label_file: "",
    role_wms: "N",
    role_lastmile: "N",
    role_contractor: "N"
};


